application: at-light-speed
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /public
  static_dir: public
- url: /
  script: home.app
  secure: always
- url: /.*
  script: app.app
  secure: always
  login: required

libraries:
- name: jinja2
  version: latest